### ISSUE TITLE
how to train with custom dataset?

### ISSUE THREAD

**Issue by xiong224** [sunset1995/DirectVoxGO#1]
Thanks for your excellent work. I have trained the models with the given datasets and they are running well. Can you tell me how to run with my own dataset? I processed the multi-view image with colmap

**Comment by RimshaTariq26** [comment]
I am currently trying to run it for my custom dataset. I processed my data with colmap but cannot generate any output using it Can you please define the steps how were you able to solve your problem

**Comment by IvanGarcia7** [comment]
Any update about how to do that?

**Comment by lij131** [comment]
Any update about how to do that?
