### ISSUE TITLE
Do camera poses all distributed in one plane affect the results?

### ISSUE THREAD

**Issue by zhouzhenghong-gt** [sunset1995/DirectVoxGO#15]
Thanks for your great work!!! @sunset1995 
If the camera pose is to shoot a circle around the object and rotate in a plane, will the bbox be very flat?
![HU`}GZF292`G9OJ6EJGIH](https://user-images.githubusercontent.com/50356920/159704952-f998ade4-25c5-402b-842b-75630d358853.png)
Experiments on my own dataset found that the reconstructed objects are also flat.

**Comment by sunset1995** [comment]
The scene bbox is automatically determined by camera frustrum (see [compute_bbox_by_cam_frustrm](https://github.com/sunset1995/DirectVoxGO/blob/13d54003538e119e9707ee5bd775d3fee05c6a5d/run.py#L165)).
The `far` distances are heuristically the maximum distance between cameras (see [inward_nearfar_heuristic](https://github.com/sunset1995/DirectVoxGO/blob/13d54003538e119e9707ee5bd775d3fee05c6a5d/lib/load_data.py#L152)).
You can hardcoded the `far` variable or introduce more rule to determine the scene bbox if you have more prior knowledge.

**Comment by zhouzhenghong-gt** [comment]
Thanks!
There was a problem with the original pose, and now the problem has been solved, thank you for your reply.
