### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by songjueun** [sunset1995/DirectVoxGO#27]
hi, thanks for your work.

I am using CUDA 11.3, Pytorch 1.11.0. When I run python run.py --config configs/lf/ship.py --render_test, I get:
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Using /home/s/.cache/torch_extensions/py39_cu113 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/s/.cache/torch_extensions/py39_cu113/adam_upd_cuda/build.ninja...
Building extension module adam_upd_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module adam_upd_cuda...
Using /home/s/.cache/torch_extensions/py39_cu113 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/s/.cache/torch_extensions/py39_cu113/render_utils_cuda/build.ninja...
Building extension module render_utils_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module render_utils_cuda...
Using /home/s/.cache/torch_extensions/py39_cu113 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/s/.cache/torch_extensions/py39_cu113/total_variation_cuda/build.ninja...
Building extension module total_variation_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module total_variation_cuda...
Using /home/s/.cache/torch_extensions/py39_cu113 as PyTorch extensions root...
No modifications detected for re-loaded extension module render_utils_cuda, skipping build step...
Loading extension module render_utils_cuda...
Using /home/s/.cache/torch_extensions/py39_cu113 as PyTorch extensions root...
Creating extension directory /home/s/.cache/torch_extensions/py39_cu113/ub360_utils_cuda...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/s/.cache/torch_extensions/py39_cu113/ub360_utils_cuda/build.ninja...
Building extension module ub360_utils_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/3] c++ -MMD -MF ub360_utils.o.d -DTORCH_EXTENSION_NAME=ub360_utils_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/s/anaconda3/lib/python3.9/site-packages/torch/include -isystem /home/s/anaconda3/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/s/anaconda3/lib/python3.9/site-packages/torch/include/TH -isystem /home/s/anaconda3/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda-11.3/include -isystem /home/s/anaconda3/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -c /home/s/DirectVoxGO/lib/cuda/ub360_utils.cpp -o ub360_utils.o 
In file included from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/c10/core/DeviceType.h:8,
                 from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/c10/core/Device.h:3,
                 from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/c10/core/Allocator.h:6,
                 from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/ATen/ATen.h:7,
                 from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/torch/extension.h:4,
                 from /home/s/DirectVoxGO/lib/cuda/ub360_utils.cpp:1:
/home/s/DirectVoxGO/lib/cuda/ub360_utils.cpp: In function ‘at::Tensor cumdist_thres(at::Tensor, float)’:
/home/s/DirectVoxGO/lib/cuda/ub360_utils.cpp:11:42: warning: ‘at::DeprecatedTypeProperties& at::Tensor::type() const’ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
   11 | #define CHECK_CUDA(x) TORCH_CHECK(x.type().is_cuda(), #x " must be a CUDA tensor")
      |                                          ^
/home/s/DirectVoxGO/lib/cuda/ub360_utils.cpp:13:24: note: in expansion of macro ‘CHECK_CUDA’
   13 | #define CHECK_INPUT(x) CHECK_CUDA(x); CHECK_CONTIGUOUS(x)
      |                        ^~~~~~~~~~
/home/s/DirectVoxGO/lib/cuda/ub360_utils.cpp:16:3: note: in expansion of macro ‘CHECK_INPUT’
   16 |   CHECK_INPUT(dist);
      |   ^~~~~~~~~~~
In file included from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/ATen/core/Tensor.h:3,
                 from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/ATen/DeviceGuard.h:4,
                 from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/ATen/ATen.h:11,
                 from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                 from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                 from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                 from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:3,
                 from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                 from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                 from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/torch/csrc/api/include/torch/all.h:8,
                 from /home/s/anaconda3/lib/python3.9/site-packages/torch/include/torch/extension.h:4,
                 from /home/s/DirectVoxGO/lib/cuda/ub360_utils.cpp:1:
/home/s/anaconda3/lib/python3.9/site-packages/torch/include/ATen/core/TensorBody.h:210:30: note: declared here
  210 |   DeprecatedTypeProperties & type() const {
      |                              ^~~~
[2/3] /usr/local/cuda-11.3/bin/nvcc  -DTORCH_EXTENSION_NAME=ub360_utils_cuda -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/s/anaconda3/lib/python3.9/site-packages/torch/include -isystem /home/s/anaconda3/lib/python3.9/site-packages/torch/include/torch/csrc/api/include -isystem /home/s/anaconda3/lib/python3.9/site-packages/torch/include/TH -isystem /home/s/anaconda3/lib/python3.9/site-packages/torch/include/THC -isystem /usr/local/cuda-11.3/include -isystem /home/s/anaconda3/include/python3.9 -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 --compiler-options '-fPIC' -std=c++14 -c /home/s/DirectVoxGO/lib/cuda/ub360_utils_kernel.cu -o ub360_utils_kernel.cuda.o 
[3/3] c++ ub360_utils.o ub360_utils_kernel.cuda.o -shared -L/home/s/anaconda3/lib/python3.9/site-packages/torch/lib -lc10 -lc10_cuda -ltorch_cpu -ltorch_cuda_cu -ltorch_cuda_cpp -ltorch -ltorch_python -L/usr/local/cuda-11.3/lib64 -lcudart -o ub360_utils_cuda.so
Loading extension module ub360_utils_cuda...
Traceback (most recent call last):
  File "/home/s/DirectVoxGO/run.py", line 593, in <module>
    data_dict = load_everything(args=args, cfg=cfg)
  File "/home/s/DirectVoxGO/run.py", line 167, in load_everything
    data_dict = load_data(cfg.data)
  File "/home/s/DirectVoxGO/lib/load_data.py", line 127, in load_data
    images, poses, render_poses, hwf, K, i_split = load_nerfpp_data(args.datadir)
  File "/home/s/DirectVoxGO/lib/load_nerfpp.py", line 122, in load_nerfpp_data
    K_flatten = np.loadtxt(tr_K[0])
IndexError: list index out of range
---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
I am not solving the above error. How can I solve this? I hope to hear from you soon!! Thank you:)

**Comment by dispoth** [comment]
Hi @songjueun, I have the same error - did you find a solution? Thanks
