### ISSUE TITLE
Cannot reproduce high quality results on Madoka and Otobai

### ISSUE THREAD

**Issue by sjtuytc** [sunset1995/DirectVoxGO#31]
Hi, thanks for your wonderful work!
I'm working on reproducing your results on Madoka and Otobai, after training via your given configs. I can only get results with low PSNRs (~31 for Madoka and ~24 for Otobai). What could be the problems there?

**Comment by sunset1995** [comment]
I think 31 and 24 are not bad for casually captured real data. Is the rendered virtual fly-through looks unexpectedly bad?

**Comment by sjtuytc** [comment]
I addressed this issue before. Thanks for your response. Looking forward to your next work!
