### ISSUE TITLE
CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

### ISSUE THREAD

**Issue by Ballzy0706** [sunset1995/DirectVoxGO#32]
Many thanks to the author for his contribution to this work,
But I'm having some difficulty implementing, which is following:

Using C:\Users\shower\AppData\Local\torch_extensions\torch_extensions\Cache\py39_cu116 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file C:\Users\shower\AppData\Local\torch_extensions\torch_extensions\Cache\py39_cu116\adam_upd_cuda\build.ninja...
Building extension module adam_upd_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
Traceback (most recent call last):

  File ~\anaconda3\lib\site-packages\torch\utils\cpp_extension.py:1808 in _run_ninja_build
    subprocess.run(

  File ~\anaconda3\lib\subprocess.py:528 in run
    raise CalledProcessError(retcode, process.args,

CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):

  File D:\DirectVoxGO-main\run.py:13 in <module>
    from lib import utils, dvgo, dcvgo, dmpigo

  File D:\DirectVoxGO-main\lib\utils.py:11 in <module>
    from .masked_adam import MaskedAdam

  File D:\DirectVoxGO-main\lib\masked_adam.py:8 in <module>
    adam_upd_cuda = load(

  File ~\anaconda3\lib\site-packages\torch\utils\cpp_extension.py:1202 in load
    return _jit_compile(

  File ~\anaconda3\lib\site-packages\torch\utils\cpp_extension.py:1425 in _jit_compile
    _write_ninja_file_and_build_library(

  File ~\anaconda3\lib\site-packages\torch\utils\cpp_extension.py:1537 in _write_ninja_file_and_build_library
    _run_ninja_build(

  File ~\anaconda3\lib\site-packages\torch\utils\cpp_extension.py:1824 in _run_ninja_build
    raise RuntimeError(message) from e

RuntimeError: Error building extension 'adam_upd_cuda'

I have tried many methods including looking for the source of extension_cpp.py or updating and modifying the version of vs and so on, but I can't solve it, I hope to get your help to achieve this work, and I have no experience in compiling so I can‘t sure where the problem is.

Additionally, my environment is Windows11, torch 1.12.0, cuda 11.6 , vs2017 and python 3.9.
Hope this extra configuration information will help you find the problem in my work better, thanks again.

**Comment by Ballzy0706** [comment]
(base) C:\Users\shower>python D:\DirectVoxGO-main\run.py --config configs/nerf/lego.py --render_test
Using C:\Users\shower\AppData\Local\torch_extensions\torch_extensions\Cache\py39_cu116 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file C:\Users\shower\AppData\Local\torch_extensions\torch_extensions\Cache\py39_cu116\adam_upd_cuda\build.ninja...
Building extension module adam_upd_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
[1/2] C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc --generate-dependencies-with-compile --dependency-output adam_upd_kernel.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=adam_upd_cuda -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\shower\anaconda3\lib\site-packages\torch\include -IC:\Users\shower\anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\shower\anaconda3\lib\site-packages\torch\include\TH -IC:\Users\shower\anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include" -IC:\Users\shower\anaconda3\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -c D:\DirectVoxGO-main\lib\cuda\adam_upd_kernel.cu -o adam_upd_kernel.cuda.o
FAILED: adam_upd_kernel.cuda.o
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\bin\nvcc --generate-dependencies-with-compile --dependency-output adam_upd_kernel.cuda.o.d -Xcudafe --diag_suppress=dll_interface_conflict_dllexport_assumed -Xcudafe --diag_suppress=dll_interface_conflict_none_assumed -Xcudafe --diag_suppress=field_without_dll_interface -Xcudafe --diag_suppress=base_class_has_different_dll_interface -Xcompiler /EHsc -Xcompiler /wd4190 -Xcompiler /wd4018 -Xcompiler /wd4275 -Xcompiler /wd4267 -Xcompiler /wd4244 -Xcompiler /wd4251 -Xcompiler /wd4819 -Xcompiler /MD -DTORCH_EXTENSION_NAME=adam_upd_cuda -DTORCH_API_INCLUDE_EXTENSION_H -IC:\Users\shower\anaconda3\lib\site-packages\torch\include -IC:\Users\shower\anaconda3\lib\site-packages\torch\include\torch\csrc\api\include -IC:\Users\shower\anaconda3\lib\site-packages\torch\include\TH -IC:\Users\shower\anaconda3\lib\site-packages\torch\include\THC "-IC:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.6\include" -IC:\Users\shower\anaconda3\Include -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr -gencode=arch=compute_86,code=compute_86 -gencode=arch=compute_86,code=sm_86 -c D:\DirectVoxGO-main\lib\cuda\adam_upd_kernel.cu -o adam_upd_kernel.cuda.o
C:/Users/shower/anaconda3/lib/site-packages/torch/include\c10/macros/Macros.h(143): warning C4067: 预处理器指令后有意外标记 - 应输入换行符
C:/Users/shower/anaconda3/lib/site-packages/torch/include\c10/macros/Macros.h(143): warning C4067: 预处理器指令后有意外标记 - 应输入换行符
C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.6/include\thrust/detail/config/cpp_dialect.h:118: warning: Thrust requires at least MSVC 2019 (19.20/16.0/14.20). MSVC 2017 is deprecated but still supported. MSVC 2017 support will be removed in a future release. Define THRUST_IGNORE_DEPRECATED_CPP_DIALECT to suppress this message.
C:/Users/shower/anaconda3/lib/site-packages/torch/include\c10/core/SymInt.h(84): warning #68-D: integer conversion resulted in a change of sign

c:\users\shower\anaconda3\lib\site-packages\torch\include\pybind11\cast.h(1429): error: too few arguments for template template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
(1507): here

c:\users\shower\anaconda3\lib\site-packages\torch\include\pybind11\cast.h(1503): error: too few arguments for template template parameter "Tuple"
          detected during instantiation of class "pybind11::detail::tuple_caster<Tuple, Ts...> [with Tuple=std::pair, Ts=<T1, T2>]"
(1507): here

2 errors detected in the compilation of "D:/DirectVoxGO-main/lib/cuda/adam_upd_kernel.cu".
adam_upd_kernel.cu
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "C:\Users\shower\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1808, in _run_ninja_build
    subprocess.run(
  File "C:\Users\shower\anaconda3\lib\subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\DirectVoxGO-main\run.py", line 13, in <module>
    from lib import utils, dvgo, dcvgo, dmpigo
  File "D:\DirectVoxGO-main\lib\utils.py", line 11, in <module>
    from .masked_adam import MaskedAdam
  File "D:\DirectVoxGO-main\lib\masked_adam.py", line 8, in <module>
    adam_upd_cuda = load(
  File "C:\Users\shower\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1202, in load
    return _jit_compile(
  File "C:\Users\shower\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1425, in _jit_compile
    _write_ninja_file_and_build_library(
  File "C:\Users\shower\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1537, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "C:\Users\shower\anaconda3\lib\site-packages\torch\utils\cpp_extension.py", line 1824, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'adam_upd_cuda'


I exported detailed error messages, it seems like the adam_upd_kernel.cu needs to be updated to fit the torch's cast.h file, but I know too little about c and c++

**Comment by Harperrrr111** [comment]
@Ballzy0706 

Hi, I met the same question. Have you addressed this issue?

**Comment by Ballzy0706** [comment]
> 
Sure.

I found that the .cpp file in this article is more demanding for my environment, just cuda==11.3 and visual studio==2019 can meet the running requirements.

And the question comes from the version of cuda code, eg. (the function "Template" in .cu file is changed across different version of cuda and gc++ that provided by visual studio). 

You can just adjust your env version same as mine, if you just want to run the code in your windows.

hope the answer could help you.

**Comment by Ballzy0706** [comment]
> @Ballzy0706
> 
> Hi, I met the same question. Have you addressed this issue?

@Harper714  Please feel free to reply if you still have problem.

**Comment by Harperrrr111** [comment]
Many thanks for your answer.

I found my error occurs only when remote debugging using pycharm, but success when directly running the code. I guess the problem is that pycharm cannot properly use g++ to compile?

**Comment by Ballzy0706** [comment]
> Many thanks for your answer.
> 
> I found my error occurs only when remote debugging using pycharm, but success when directly running the code. I guess the problem is that pycharm cannot properly use g++ to compile?

Happy to hear that. 

The reason about your description, I could not locate your problem exactly. I guess that the problem with pycharm may be related to the environment variables you set, which are different from the env when you run the code directly.

**Comment by Harperrrr111** [comment]
Yes, I guess so. I will try again~

**Comment by Ailon-Island** [comment]
I met the same problem but I didn't have the priviliage to upgrade g++ and CUDA. 

Instead, I solve it by adding `extra_cflags=["-std=c++14"], extra_cuda_cflags=["-std=c++14"]` in every call of `torch.utils.cpp_extension.load`. 

Besides, I also changes PyTorch's source code a bit according to [this blog](https://zhuanlan.zhihu.com/p/468605263). That is, in `.../site-package/torch/include/torch/csrc/api/include/torch/nn/cloneable.h`, line 46, 58, 70,
```
copy->parameters_.size() == parameters_.size()

copy->buffers_.size() == buffers_.size()

copy->children_.size() == children_.size()
```
are modified into
```
copy->parameters_.size() == this -> parameters_.size()

copy->buffers_.size() == this -> buffers_.size()

copy->children_.size() == this -> children_.size()
```
This is not quite an elegant solution.
