### ISSUE TITLE
Problem with processed Tanks and Temples

### ISSUE THREAD

**Issue by danperazzo** [sunset1995/DirectVoxGO#4]
Hello everyone, thank you for releasing this great technique. I was testing you technoque on you processed tenaks and Temples scenes, however, I noticed that the Ignatius scene seems to be having a problem with the Intrinsics. It is formated in a diferent way than the other scenes and the folder structure is also different. Because of this, I could not test in this scene. Thank you for the attention!

**Comment by apchenstu** [comment]
Very nice work! Same issue on my side, it would be really helpful if the author can help with updating the intrinsic. Thanks in advance.

**Comment by sunset1995** [comment]
Sorry for missing this thread. Below is the `intrinsics.txt` in compatible format:
```txt
1166.564936839068 0.0 960.0 0.0
0.0 1166.564936839068 540.0 0.0
0.0 0.0 1.0 0.0
0.0 0.0 0.0 1.0
```
