### ISSUE TITLE
error on "render_utils_cuda.sample_pts_on_rays"

### ISSUE THREAD

**Issue by ChambinLee** [sunset1995/DirectVoxGO#42]
Thanks for the amazing work. I run the scrip likes "readme.md" says. But the error appear at render_utils_cuda.sample_pts_on_rays. Here is the error info:

> Using /home/chambin/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/chambin/.cache/torch_extensions/py38_cu113/adam_upd_cuda/build.ninja...
Building extension module adam_upd_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module adam_upd_cuda...
Using /home/chambin/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/chambin/.cache/torch_extensions/py38_cu113/render_utils_cuda/build.ninja...
Building extension module render_utils_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module render_utils_cuda...
Using /home/chambin/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/chambin/.cache/torch_extensions/py38_cu113/total_variation_cuda/build.ninja...
Building extension module total_variation_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module total_variation_cuda...
Using /home/chambin/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
No modifications detected for re-loaded extension module render_utils_cuda, skipping build step...
Loading extension module render_utils_cuda...
Using /home/chambin/.cache/torch_extensions/py38_cu113 as PyTorch extensions root...
Detected CUDA files, patching ldflags
Emitting ninja build file /home/chambin/.cache/torch_extensions/py38_cu113/ub360_utils_cuda/build.ninja...
Building extension module ub360_utils_cuda...
Allowing ninja to set a default number of workers... (overridable by setting the environment variable MAX_JOBS=N)
ninja: no work to do.
Loading extension module ub360_utils_cuda...
Loaded blender (120, 200, 200, 4) torch.Size([160, 4, 4]) [200, 200, 274.7477419454622] ./data/nerf_synthetic/plane_grass
train: start
compute_bbox_by_cam_frustrm: start
/home/chambin/anaconda3/envs/dvgo2/lib/python3.8/site-packages/torch/functional.py:568: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at  /opt/conda/conda-bld/pytorch_1646755903507/work/aten/src/ATen/native/TensorShape.cpp:2228.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
compute_bbox_by_cam_frustrm: xyz_min tensor([-3.0437, -3.0213, -2.6208])
compute_bbox_by_cam_frustrm: xyz_max tensor([3.0345, 3.0083, 2.3107])
compute_bbox_by_cam_frustrm: finish
scene_rep_reconstruction (coarse): train from scratch
scene_rep_reconstruction (coarse): use dense voxel grid
dvgo: set density bias shift to tensor([-13.8155], device='cpu')
dvgo: voxel_size       tensor(0.0561)
dvgo: world_size       tensor([108, 107,  87])
dvgo: voxel_size_base  tensor(0.0561)
dvgo: voxel_size_ratio tensor(1.)
create_optimizer_or_freeze_model: param density lr 0.1
create_optimizer_or_freeze_model: param k0 lr 0.1
create_optimizer_or_freeze_model: param rgbnet not exist
get_training_rays: start
get_training_rays: finish (eps time: 0.024027109146118164 sec)
dvgo: voxel_count_views start
dvgo: voxel_count_views finish (eps time: 1.5023679733276367 sec)
  0%|                                                                                        | 0/5000 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "run.py", line 630, in <module>
    train(args, cfg, data_dict)
  File "run.py", line 541, in train
    scene_rep_reconstruction(
  File "run.py", line 446, in scene_rep_reconstruction
    render_result = model(
  File "/home/chambin/anaconda3/envs/dvgo2/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/chambin/Documents/projects/DirectVoxGO-main/lib/dvgo.py", line 310, in forward
    ray_pts, ray_id, step_id = self.sample_ray(
  File "/home/chambin/Documents/projects/DirectVoxGO-main/lib/dvgo.py", line 290, in sample_ray
    ray_pts, mask_outbbox, ray_id, step_id, N_steps, t_min, t_max = render_utils_cuda.sample_pts_on_rays(
RuntimeError: value cannot be converted to type int without overflow
`

My environment info is:
`ubuntu 21
cuda 11.3
torch 1.11`

Could anyone tell me how to fix this error? Thanks in advance!

**Comment by JakeXin7** [comment]
Hi, I met the same problem. Have you solved it?
