### ISSUE TITLE
About world_size for density

### ISSUE THREAD

**Issue by DRosemei** [sunset1995/DirectVoxGO#6]
Thanks for your great work. I want to know where you set "world_size" for density constuction? And what's the shape of it?
https://github.com/sunset1995/DirectVoxGO/blob/main/lib/dvgo.py#L48

**Comment by sunset1995** [comment]
It's automatically derived from the `xyz_min`, `xyz_max` (derived from camera poses), and the expected total number of voxels `num_voxels` (a hyperparameter).

**Comment by DRosemei** [comment]
> It's automatically derived from the `xyz_min`, `xyz_max` (derived from camera poses), and the expected total number of voxels `num_voxels` (a hyperparameter).

Thanks for your reply and I found it when I ran your code:)
