### ISSUE TITLE
Missing requirement `pytorch_scatter`

### ISSUE THREAD

**Issue by fxmarty** [sunset1995/DirectVoxGO#8]
Hello, with the recent updates there is a missing requirement `pytorch_scatter`.

I don't know what is the best to go for putting it in `requirements.txt` as the version depends on PyTorch version and CUDA version, see https://github.com/rusty1s/pytorch_scatter#pytorch-1100 , so I let you find a way.

Typically, the format is `pip install torch-scatter -f https://data.pyg.org/whl/torch-${TORCH_VERSION}+${CUDA_VERSION}.html` where `${TORCH_VERSION}+${CUDA_VERSION}` is e.g. `1.10.0+cu111`.

Thank you!

**Comment by sunset1995** [comment]
Readme updated for this. Thanks!
